services:

  backend:
    build: backend
    
    hostname: backend
   
    ports:
      - "8000:8000"
    
   
  frontend:
    build: frontend
    hostname: frontend
   
    environment:
      - BACKEND_URL=BACKEND_URL
    ports:
      - "9000:9000"
    links:
      - backend
    depends_on:
      - backend
    

networks: {}